image:
  file: .gitpod.Dockerfile
tasks:
  - name: Starting Project
    init: composer create-project laravel/laravel:^8.0 laravel &&
      mkdir -p laravel/packages/badaso/core &&
      mv {,.}* laravel/packages/badaso/core 2>/dev/null; true &&
      cd laravel &&
      cp packages/badaso/core/.gitpod/app.php config/app.php &&
      cp packages/badaso/core/.gitpod/AppServiceProvider.php app/Providers/AppServiceProvider.php &&
      cp packages/badaso/core/.gitpod/composer.json composer.json &&
      cp packages/badaso/core/.gitpod/webpack.mix.js webpack.mix.js &&
      cp .env.example .env &&
      sed -i 's/http:\/\/localhost//g' .env &&
      sed -i 's/FILESYSTEM_DRIVER=local/FILESYSTEM_DRIVER=public/g' .env &&
      sed -i "s|APP_URL=|APP_URL=${GITPOD_WORKSPACE_URL}|g" .env &&
      sed -i "s|APP_URL=https://|APP_URL=https://8000-|g" .env &&
      composer update &&
      php artisan key:generate &&
      mysql -u root -e "create database laravel"
    command: php artisan badaso:setup --force &&
      php artisan migrate &&
      php artisan db:seed --class="Database\Seeders\Badaso\BadasoSeeder" &&
      php artisan badaso:admin admin@admin.com --name=admin --username=admin --password=admin --confirm_password=admin --create &&
      php artisan storage:link &&
      php artisan l5-swagger:generate &&
      npm install &&
      npm run dev &&
      php artisan serve --host=0.0.0.0
ports:
  - port: 8000
    onOpen: open-browser
  - port: 3306
    onOpen: ignore
vscode:
  extensions:
    - bmewburn.vscode-intelephense-client
    - MehediDracula.php-namespace-resolver
    - junstyle.php-cs-fixer
    - PKief.material-icon-theme
