name: PHP Stan

on:
  push:
    branches:
      - "master"
  pull_request:
    types:
      - synchronize
      - opened
      - edited
      - reopened

jobs:
  test:
    # Setup ubuntu latest
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [8.0]
        laravel: ["8.*"]
        laravel-require: [8.0]

    name: "PHP ${{ matrix.php }} / Laravel ${{ matrix.laravel }}"

    steps:
      - uses: actions/checkout@master

      # Configure PHP
      - name: Select PHP version
        uses: shivammathur/setup-php@master
        with:
          php-version: "${{ matrix.php }}"
          extensions: mbstring, pdo_sqlite, fileinfo, gd, php_pgsql
          coverage: none

      # Install legacy factories for Laravel 8/9
      - name: Install legacy factories for Laravel
        run: composer create-project laravel/laravel:^${{matrix.laravel-require}} laravel

      # Display installed laravel version
      - name: Show laravel version
        run: cd laravel &&
          composer show laravel/framework

      # Laravel require badaso core
      - name: Laravel file configuration
        run: git branch &&
          cd laravel &&
          composer require badaso/core:dev-${GITHUB_HEAD_REF} &&
          composer update --no-interaction

      # Laravel setup
      - name: Laravel setup
        run: cd laravel &&
          php artisan badaso:setup --force

      # Badaso Core Test PHPStan
      - name: Badaso core test PHPStan
        run: cd laravel && 
             ./vendor/bin/phpstan analyse -c vendor/badaso/core/phpstan.neon.dist


