name: PHP Stan

on:
  push:
    branches:
      - "master"
  pull_request:
    types:
      - synchronize
      - opened
      - edited
      - reopened

jobs:
  test:
    # Setup ubuntu latest
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    name: "PHPStan Badaso Core"

    steps:
      # Run composer badaso core
      - name: Composer update
        run: composer update --no-interaction

      # Badaso Core Test PHPStan
      - name: Badaso core test PHPStan
        run: ./vendor/bin/phpstan analyse -c phpstan.neon.dist


