export default {
  auth: {
    login: '/badaso-api/v1/auth/login',
    logout: '/badaso-api/v1/auth/logout',
    forgotPassword: '/badaso-api/v1/auth/forgot-password',
    resetPassword: '/badaso-api/v1/auth/reset-password',
    register: '/badaso-api/v1/auth/register',
    verify: '/badaso-api/v1/auth/verify',
    refreshToken: '/badaso-api/v1/auth/refresh-token',
    user: '/badaso-api/v1/auth/user',
    changePassword: '/badaso-api/v1/auth/change-password'
  },
  bread: {
    browse: '/badaso-api/v1/breads',
    read: '/badaso-api/v1/breads/read',
    readBySlug: '/badaso-api/v1/breads/read-by-slug',
    edit: '/badaso-api/v1/breads/edit',
    add: '/badaso-api/v1/breads/add',
    delete: '/badaso-api/v1/breads/delete',
    table: '/badaso-api/v1/breads/table',
  },
  configuration: {
    applyable: '/badaso-api/v1/configurations/applyable',
    browse: '/badaso-api/v1/configurations',
    read: '/badaso-api/v1/configurations/read',
    edit: '/badaso-api/v1/configurations/edit',
    editMultiple: '/badaso-api/v1/configurations/edit-multiple',
    add: '/badaso-api/v1/configurations/add',
    delete: '/badaso-api/v1/configurations/delete',
  },
  menu: {
    browse: '/badaso-api/v1/menus',
    read: '/badaso-api/v1/menus/read',
    edit: '/badaso-api/v1/menus/edit',
    add: '/badaso-api/v1/menus/add',
    delete: '/badaso-api/v1/menus/delete',
    browseItem: '/badaso-api/v1/menus/item',
    arrangeItems: '/badaso-api/v1/menus/arrange-items',
    browseItemByKey: '/badaso-api/v1/menus/item-by-key',
    readItem: '/badaso-api/v1/menus/item/read',
    editItem: '/badaso-api/v1/menus/item/edit',
    editItemOrder: '/badaso-api/v1/menus/item/edit-order',
    addItem: '/badaso-api/v1/menus/item/add',
    deleteItem: '/badaso-api/v1/menus/item/delete',
  },
  permission: {
    browse: '/badaso-api/v1/permissions',
    read: '/badaso-api/v1/permissions/read',
    edit: '/badaso-api/v1/permissions/edit',
    add: '/badaso-api/v1/permissions/add',
    delete: '/badaso-api/v1/permissions/delete',
    deleteMultiple: '/badaso-api/v1/permissions/delete-multiple',
  },
  role: {
    browse: '/badaso-api/v1/roles',
    read: '/badaso-api/v1/roles/read',
    edit: '/badaso-api/v1/roles/edit',
    add: '/badaso-api/v1/roles/add',
    delete: '/badaso-api/v1/roles/delete',
    deleteMultiple: '/badaso-api/v1/roles/delete-multiple',

    permissions: '/badaso-api/v1/role-permissions/all-permission',
    addPermissions: '/badaso-api/v1/role-permissions/add-edit',
  },
  user: {
    browse: '/badaso-api/v1/users',
    read: '/badaso-api/v1/users/read',
    edit: '/badaso-api/v1/users/edit',
    add: '/badaso-api/v1/users/add',
    delete: '/badaso-api/v1/users/delete',
    deleteMultiple: '/badaso-api/v1/users/delete-multiple',

    roles: '/badaso-api/v1/user-roles/all-role',
    addRoles: '/badaso-api/v1/user-roles/add-edit',
  },
  data: {
    component: '/badaso-api/v1/data/components',
    filterOperator: '/badaso-api/v1/data/filter-operators'
  },
  entity: '/badaso-api/v1/entities'
}